export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAIL = "REGISTER_USER_FAIL";

export const ADD_USER_REQUEST = "NEW_PRODUCT_REQUEST";
export const ADD_USER_SUCCESS = "NEW_PRODUCT_SUCCESS";
export const ADD_USER_RESET = "NEW_PRODUCT_RESET";
export const ADD_USER_FAIL = "NEW_PRODUCT_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
